# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
chruby ruby-2.0

# homebrew
PATH=/usr/local/bin:/usr/local/sbin:$PATH

# VirtualBox & Vagrant
PATH=$PATH:/Applications/VirtualBox.app/Contents/MacOS

# vim is the editor
export EDITOR='vi'

# export PATH
export PATH

# export MANPATH WHY IS THIS ALL FUCKED UP BDSF:SDFSK:DFSKDFSDF
# MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
# MANPATH=$MANPATH:/usr/share/man
# MANPATH="$(brew --prefix)/share/man:$MANPATH"
#
# export MANPATH


# shell
export SHELL=/bin/zsh

# vim
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
bindkey 'jk' vi-cmd-mode

# less
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS=" -R"

#
# Aliases
#

alias hiddenon='defaults write com.apple.finder AppleShowAllFiles -boolean true'
alias hiddenoff='defaults delete com.apple.finder AppleShowAllFiles'
alias dedupe="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user"
alias 755="find . -type d -print0 | xargs -0 chmod 0755"
alias 644="find . -type f -print0 | xargs -0 chmod 0644"
alias dot_cleaner="sudo find / -name ".DS_Store" -depth -exec rm {} \; && dot_clean ~/"
alias maintenance='sudo periodic daily weekly monthly'
alias clear='figlet -f colossal "CTRL - L IDIOT"'
alias dirs='dirs -v'

# Tmux
alias tmux="tmux -2"
alias layout=''

# SSH
alias ssh='TERM=xterm ssh'

# vim
alias vi='mvim -v'

# Bundler
alias bcw='bundle exec compass watch'
alias beg='bundle exec guard'
alias bcwc='bundle exec compass compile --force'

# LS
# alias ls='ls --color=auto'
# alias ll='ls -larth --color=auto'

# Compass
alias cwc='compass compile --force'
alias cw='compass watch'

# Vagrant
alias vu="vagrant up"
alias vd="vagrant destroy"
alias vh="vagrant halt"
alias vr="vagrant reload"
alias vst="vagrant status"
alias vs="vagrant ssh"
alias vp="vagrant provision"
alias vssh='TERM=xterm vagrant ssh'

# unsetopt auto_pushd
